config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/notes/dashboard', to: 'notes#dashboard'
  resources :notes
  root 'notes#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /notes or /notes.json
  def index
    @notes = Note.where(user_id: current_user.id)
  end

  # GET /notes/dashboard
  def dashboard
    @notes = Note.where(user_id: current_user.id)
  end

  # GET /notes/1 or /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes or /notes.json
  def create
    note = Note.new(note_params)
    note.user_id = current_user.id
    @note = note

    respond_to do |format|
      if @note.save
        # send note id through the headers to use into the tests
        response.set_header("note_id", "#{@note.id}")
        format.html { redirect_to @note, notice: "Note was successfully created." }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1 or /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        response.set_header("note_id", "#{@note.id}")
        format.html { redirect_to @note, notice: "Note was successfully updated." }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1 or /notes/1.json
  def destroy
    respond_to do |format|
      if @note
        @note.destroy
        format.html { redirect_to notes_url, notice: "Note was successfully destroyed." }
        format.json { head :no_content }
      else
        format.html { render :index, status: :not_found }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
      rescue ActiveRecord::RecordNotFound
    end

    # Only allow a list of trusted parameters through.
    def note_params
      params.require(:note).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg sticky-top navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="">Notes App</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarScroll">
            <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
              <li class="nav-item">
                <%= link_to "Home", root_path, class:"nav-link" %>
            </li>
            <% if user_signed_in? %>
                <li class="nav-item">
                    <%= link_to "Notes", notes_path, class:"nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to "Dashboard", notes_dashboard_path, class:"nav-link" %>
                </li>
            <% end %>
            </ul>
            <ul class="navbar-nav mr-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
                <% if user_signed_in? %>
                    <li class="nav-item">
                        <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link" %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link" %>
                    </li>
                <% else %>
                    <li class="nav-item">
                        <%= link_to "Sign In", new_user_session_path, class:"nav-link" %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
                    </li>
                <% end %>
              </ul>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsToDoApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,700;1,100;1,300;1,400;1,500&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/8e0fadaa96.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container mt-4">
      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>
      <%= yield %>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
  </body>
</html>

app/views/notes/_form.html.erb
<%= form_with(model: note) do |form| %>
  

  <div class="col">
    <div class="row">
      <% if note.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

          <ul>
            <% note.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    </div>
    <div class="row">
      <div class="col-md-5 mx-auto">
        <div class="card shadow">
          <div class="card-body">
            <div class="form-group mb-2">
              <% form.label :title %>
              <%= form.text_field :title, class:"form-control", placeholder:"Note title" %>
            </div>
            <div class="form-group mb-2">
              <% form.label :description %>
              <%= form.text_area :description, class:"form-control", placeholder:"Description" %>
            </div>
            <!-- <div class="form-group mb-2">
              <% form.label :user_id %>
              <%= form.number_field :user_id, id: :note_user_id, class:"form-control", placeholder:"user id", value: current_user.id, type: :hidden %>
            </div> -->
          </div>
          <div class="card-footer">
            <div class="actions d-flex justify-content-end">
              <%= form.submit class:'btn btn-primary' %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/notes/dashboard.html.erb
<%= react_component("Dashboard", { notes: @notes }) %>

app/views/notes/edit.html.erb
<div class="row">
    <div class="col">
        <div class="row text-center">
            <h1>Editing Note</h1>
        </div>
        <div class="row">
            <%= render 'form', note: @note %>
        </div>
        <div class="row mt-4">
            <div class="col-md-5 mx-auto">
                <hr>
                <%= link_to 'Show', @note %> |
                <%= link_to 'Back', notes_path %>
                <hr>
            </div>
        </div>
    </div>
</div>

app/views/notes/index.html.erb
<div class="row">
  <div class="col">
    <div class="row">
      <%= react_component("HelloWorld/SayHelloWorld", { greeting: "Hello World!", children: "Children Value" }) %>
    </div>
    <div class="row d-flex align-items-center">
        <div class="col">
          <h1>Notes</h1>
        </div>
        <div class="col d-flex justify-content-end">
          <%= link_to 'New Note +', new_note_path, class: 'btn btn-primary' %>
        </div>
      <hr>
    </div>
    <div class="row">
      <% @notes.each do |note| %>
      <div class="col-md-3 mt-3">
        <%= react_component("Card", { title: note.title, description: note.description, actions: { edit: edit_note_path(note), delete: "notes/delete/#{note.id}" }  }) %>
      </div>
      <!-- <%= link_to 'Edit', edit_note_path(note), class:'btn btn-primary btn-sm mb-1' %>
      <%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-danger btn-sm' %> -->
    <% end %>
    </div>
  </div>
</div>

app/views/notes/new.html.erb
<div class="row">
    <div class="col">
        <div class="row text-center">
            <h1>New Note</h1>
        </div>
        <div class="row">
            <%= render 'form', note: @note %>
        </div>
        <div class="row">
            <div class="col-md-5 mx-auto mt-4">
                <hr>
                <%= link_to 'Go Back', notes_path %>
                <hr>
            </div>
        </div>
    </div>
</div>

app/views/notes/show.html.erb
<div class="row">
    <div class="col">
        <div class="row">
            <div class="col-md-4 mx-auto">
                <div class="card shadow">
                    <div class="card-body">
                        <h4><%= @note.title %></h4>
                        <hr>
                        <p style="text-align: justify;"><%= @note.description %></p>
                        <div class="fw-light text-end">
                            <%= @note.created_at.strftime("%a, %B %d, %Y") %>
                        </div>
                    </div>
                    <div class="card-footer d-flex align-items-center justify-content-end">
                        <!-- <%= link_to 'Edit', edit_note_path(@note), class:'btn btn-primary btn-sm me-2' %> -->
                        <%= link_to 'Destroy', @note, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-danger btn-sm' %>
                    </div>
                </div>
            </div>
        </div>
        <div class="row mt-4">
            <div class="col-md-4 mx-auto">
                <hr>
                <%= link_to 'Edit', edit_note_path(@note) %> |
                <%= link_to 'Back', notes_path %>
                <hr>
            </div>
        </div>
    </div>
</div>